apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: flask-sa
      containers:
      - name: backend
        image: 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_SECRET_NAME
          value: "rds!cluster-2afe16bc-dff3-4f93-af70-f33af4169d3b"
        - name: AWS_REGION
          value: "ap-south-1"
      #  - name: JWT_SECRET
      #    valueFrom:
      #      secretKeyRef:
      #        name: backend-secrets
      #        key: jwt 
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000