name: Build and Push to ECR backend
on:
  push:
    paths:
      - 'backend/**'
      - 'k8s-manifest/backend/**'
      - '.github/workflows/backend.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-push-APi-flask:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
          role-session-name: github-assume
          aws-region: ap-south-1

      - name: Login to Amazon ECR # login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image 
        run: |
          docker build -t 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:${{ github.sha }} ./backend
          docker tag 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:${{ github.sha }} 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest

      - name: Push Docker Image 
        run: |
          docker push 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:${{ github.sha }}
          docker push 199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:latest

     
  
  deploy:
    name: Deploy App and ALB Ingress
    needs: build-push-APi-flask  # Optional: Run sequentially after job1
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: test-eks
      AWS_REGION: ap-south-1
      NAMESPACE: default

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::199570228070:role/oidc-demo-role
          role-session-name: github-assume
          aws-region: ap-south-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name demo6-eks

      - name: Verify Cluster Access
        run: |
          kubectl get nodes
                

      - name: Deployment + Service + Ingress
        run: |
         sed -i 's@CONTAINER_IMAGE@'"199570228070.dkr.ecr.ap-south-1.amazonaws.com/flask-app:${{ github.sha }}"'@' k8s-manifest/backend/backend-deployment.yaml
         kubectl apply -f k8s-manifest/backend/configmap.yaml
         kubectl apply -f k8s-manifest/backend/service-account.yml
         kubectl apply -f k8s-manifest/backend/backend-deployment.yaml
         kubectl apply -f k8s-manifest/backend/ingress-backend.yaml



  